### ISSUE TITLE
Mass sg & pl format seems incorrect. Causing issues with generated UoMs.

### ISSUE THREAD

**Issue by SamGrayson** [harrydehix/simple-units#10]
First off, thank you for the awesome library. It's making our UoM conversions much easier.

Just a small issue we've noticed here:
https://github.com/harrydehix/simple-units/blob/58ddee457f799c4b202f8bbc14bf7822a017cbf7/src/units/groups/mass.ts#L12-L18

- It appears the mass base unit has the wrong pl.
- Should it be?...
```
long: {
            sg: ["%0gram", "%0gramme"],
            pl: ["%0grams", "%0grammes"],
        }
```

This is causing issues down the line when trying to leverage long names for generated UoMs.
- ex: kilogram returns: `pl: ['kilogram', 'kilograms']`

I haven't had a chance yet to check out the other groups.

**Comment by harrydehix** [comment]
Thank you very much, I'll fix this today!

**Comment by harrydehix** [comment]
Should be fixed now!
